version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - ../etsource:/etsource:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
      - storage:/app/storage
    env_file:
      - .docker/env/development/database
      - .docker/env/development/web
    tmpfs:
      - /tmp
    depends_on:
      database:
        condition: service_healthy
    tty: true
    stdin_open: true

  database:
    image: mariadb:10
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .docker/env/development/database
    healthcheck:
      test: mysqladmin ping
      interval: 2s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  bundle:
  db_data:
  node_modules:
  packs:
  rails_cache:
  storage:
