development: &default
  adapter: mysql2
  database: <%= ENV.fetch('MYSQL_DATABASE', 'etengine_development') %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: 3306
  username: <%= ENV.fetch('MYSQL_USER', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', '') %>
  encoding: utf8
  timeout: 5000
  pool: 5

test:
  <<: *default
  database: etengine_test

production:
  <<: *default
  database: etengine_production

staging:
  <<: *default
  database: etengine_staging
