etsource_lazy_load_dataset: false
etsource_export: tmp/etsource
etsource_working_copy: <%= ENV.fetch('ETSOURCE_PATH', '/app/etsource') %>

etmodel_uri: https://tyndp2026.energytransitionmodel.com

auth:
  issuer: https://tyndp2026.engine.energytransitionmodel.com
