etsource_lazy_load_dataset: false
etsource_export: tmp/etsource
etsource_working_copy: <%= ENV.fetch('ETSOURCE_PATH', '/app/etsource') %>

etmodel_uri: https://beta.energytransitionmodel.com

auth:
  issuer: https://beta.engine.energytransitionmodel.com

identity:
  client_uri: https://beta.my.energytransitionmodel.com