etsource_lazy_load_dataset: false
etsource_export: tmp/etsource
etsource_working_copy: <%= ENV.fetch('ETSOURCE_PATH', '/app/etsource') %>

etmodel_uri: https://beta.energytransitionmodel.com

auth:
  issuer: https://beta.engine.energytransitionmodel.com
  default_sign_out_url: https://beta.energytransitionmodel.com
