name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 6 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has had no activity for 60 days. Removing the "Stale" label or posting a comment will
          prevent it from being closed automatically in 7 days. You can also add the "Pinned" label to
          ensure it isn't marked as stale in the future.
        exempt-issue-labels: 'Pinned'
        stale-pr-message: |
          This pull request has had no activity for 60 days. Removing the "Stale" label or posting a comment
          will prevent it from being closed automatically in 7 days. You can also add the "Pinned" label to
          ensure it isn't marked as stale in the future.
        exempt-pr-labels: 'Pinned'
