name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 6 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity for sixty days. Remove the "Stale" label or post a comment if you do not wish it to be closed in seven days.'
        exempt-issue-labels: 'Pinned'
        stale-pr-message: 'This pull request has had no activity for sixty days. Remove the "Stale" label or post a comment if you do not wish it to be closed in seven days.'
        exempt-pr-labels: 'Pinned'
